In [1]:
import numpy as np
import math

In [2]:
test_array = np.random.randint(10, size=(10, 4))

In [3]:
test_array


array([[6, 9, 9, 0],
       [5, 0, 5, 3],
       [8, 1, 3, 9],
       [8, 1, 0, 6],
       [0, 9, 0, 9],
       [4, 7, 2, 2],
       [3, 2, 9, 6],
       [6, 6, 5, 3],
       [5, 3, 0, 6],
       [2, 1, 7, 9]])

In [4]:
(test_array[0]-test_array[1])**2

array([ 1, 81, 16,  9], dtype=int32)

In [5]:
c1 = test_array[0]

In [6]:
c1

array([6, 9, 9, 0])

In [7]:
test2 = np.delete(test_array, 0, 0)

In [8]:
test2

array([[5, 0, 5, 3],
       [8, 1, 3, 9],
       [8, 1, 0, 6],
       [0, 9, 0, 9],
       [4, 7, 2, 2],
       [3, 2, 9, 6],
       [6, 6, 5, 3],
       [5, 3, 0, 6],
       [2, 1, 7, 9]])

In [9]:
result = np.zeros((9,1))
for row in range(len(test2)):
    result[row] = sum((test2[row] - c1)**2)
    

In [10]:
result

array([[107.],
       [185.],
       [185.],
       [198.],
       [ 61.],
       [ 94.],
       [ 34.],
       [154.],
       [165.]])

In [11]:
max(result)

array([198.])

In [12]:
ind = np.unravel_index(np.argmax(result, axis=None), len(result))

In [13]:
ind

(3,)

In [14]:
test2[ind]

array([0, 9, 0, 9])

In [15]:
c2 = c1.append(test2[ind])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
centroids = c1(test2[ind])

In [16]:
centroids = np.stack((c1, test2[ind]), axis=0)

In [17]:
centroids

array([[6, 9, 9, 0],
       [0, 9, 0, 9]])

In [18]:
test3 = np.delete(test2, ind, 0)

In [19]:
test3

array([[5, 0, 5, 3],
       [8, 1, 3, 9],
       [8, 1, 0, 6],
       [4, 7, 2, 2],
       [3, 2, 9, 6],
       [6, 6, 5, 3],
       [5, 3, 0, 6],
       [2, 1, 7, 9]])