In [64]:
import numpy as np
import math

In [15]:
test_array = np.random.randint(10, size=(10, 4))

In [16]:
test_array


array([[1, 7, 2, 9],
       [9, 8, 1, 7],
       [6, 6, 4, 4],
       [8, 9, 3, 6],
       [1, 4, 3, 3],
       [7, 7, 9, 6],
       [0, 6, 4, 3],
       [7, 5, 0, 5],
       [9, 1, 2, 2],
       [7, 3, 5, 0]])

In [17]:
(test_array[0]-test_array[1])**2

array([64,  1,  1,  4], dtype=int32)

In [18]:
c1 = test_array[0]

In [19]:
c1

array([1, 7, 2, 9])

In [28]:
test2 = np.delete(test_array, 0, 0)

In [29]:
test2

array([[9, 8, 1, 7],
       [6, 6, 4, 4],
       [8, 9, 3, 6],
       [1, 4, 3, 3],
       [7, 7, 9, 6],
       [0, 6, 4, 3],
       [7, 5, 0, 5],
       [9, 1, 2, 2],
       [7, 3, 5, 0]])

In [70]:
result = np.zeros((9,1))
for row in range(len(test2)):
    result[row] = sum((test2[row] - c1)**2)
    

In [71]:
result

array([[ 70.],
       [ 55.],
       [ 63.],
       [ 46.],
       [ 94.],
       [ 42.],
       [ 60.],
       [149.],
       [142.]])

In [72]:
max(result)

array([149.])

In [76]:
ind = np.unravel_index(np.argmax(result, axis=None), len(result))

In [77]:
ind

(7,)

In [78]:
test2[ind]

array([9, 1, 2, 2])

In [79]:
c2 = c1.append(test2[ind])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [82]:
centroids = c1(test2[ind])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [84]:
centroids = np.concatenate((c1, test2[ind]), axis=0)

In [85]:
centroids

array([1, 7, 2, 9, 9, 1, 2, 2])